- hosts: localhost
  connection: local
  tasks:
    - name: Install Zabbix agent
      yum: state=latest name=zabbix22-agent
    - name: Install CNC Zabbix custom scripts
      yum: name=nc-zabbix-custom-scripts state=latest
    - name: Fix Zabbix config file
      lineinfile: dest=/etc/zabbix_agentd.conf state=present regexp='^(.*)HOSTNAME(.*)$' line='' backrefs=yes
    - name: Fix Zabbix HOME
      lineinfile: dest=/etc/passwd state=present regexp='^(.*)\/var\/lib\/zabbix(.*)$' line='\1/home/zabbix\2' backrefs=yes
    - name: Change Zabbix to active agent
      lineinfile: dest=/etc/zabbix_agentd.conf state=present regexp='^Server\=127\.0\.0\.1\,(.*)$' line='Server=127.0.0.1,\1\nServerActive=127.0.0.1,\1' backrefs=yes
    - name: Restart crond to use new locations
      service: name=crond state=restarted
    - name: Enable Zabbix agent
      service: name=zabbix-agent state=restarted enabled=yes
