- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="Hostname for Opsstack config is not defined"
      when: opsstack_hostname is not defined

    - name: Save SELinux settings
      set_fact: selinux="{{ ansible_selinux }}"
      when: ansible_selinux and ansible_selinux.status != "disabled"

    - name: Disable SElinux
      selinux: state=disabled
      when: selinux is defined

    - name: Ensure nc-zabbix-agent is installed
      package: name={{item}} state=latest
      with_items:
        - nc-zabbix-agent
        - nc-zabbix-scripts

    - name: Setup nc-zabbix hostname
      replace:
        dest: /etc/nc_zabbix/nc_zabbix_agentd.conf
        regexp: '# Hostname='
        replace: "Hostname={{opsstack_hostname}}"
        backup: no

    - name: Change Server Active list for USA
      replace:
        dest: /etc/nc_zabbix/nc_zabbix_agentd.conf
        regexp: '^ServerActive.*'
        replace: 'ServerActive = {{ zabbix_host_list }}'
        backup: no

    - name: Restart crond to use new locations
      service: name=crond state=restarted

    - name: Enable Zabbix agent
      service: name=nc-zabbix-agent state=restarted enabled=yes

    - name: Enable SElinux
      selinux: state="{{ selinux.config_mode }}" policy="{{ selinux.type }}"
      when: selinux is defined
