- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="Hostname for Opsstack config is not defined"
      when: opsstack_hostname is not defined

    - name: Create lock file
      file: path=../locks/zabbix.lock state=touch mode=0000

    - name: Save SELinux settings
      set_fact: selinux="{{ ansible_selinux }}"
      when: ansible_selinux and ansible_selinux.config_mode != "disabled"

    - name: Disable SElinux
      selinux: state=disabled
      when: selinux is defined

    - include: ./base_monitoring/rhel6.yml
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6) or ansible_distribution == 'Amazon'

    - include: ./base_monitoring/rhel7.yml
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

    - include: ./base_monitoring/debian8.yml
      when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 8

    - include: ./base_monitoring/debian7.yml
      when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 7

    - name: Enable SElinux
      selinux: state="{{ selinux.config_mode }}" policy="{{ selinux.type }}"
      when: selinux is defined
