- hosts: localhost
  connection: local
  tasks:
    - yum: state=present name=http://repo.service.chinanetcloud.com/yum/el6/base/x86_64/nc-repo-1.0.0-1.el6.noarch.rpm
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6) or ansible_distribution == 'Amazon'

    - yum: state=present name=http://repo.service.chinanetcloud.com/yum/el7/base/x86_64/nc-repo-1.0.0-1.el7.noarch.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
