- hosts: localhost
  connection: local
  tasks:
    - name: Check Filebeat config is provided
      fail: msg="FILEBEAT_CONF is undefined"
      when: FILEBEAT_CONF is undefined

    - name: Install FileBeat (rhel)
      package:
        name: filebeat
        state: latest
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - name: Install FileBeat (debian)
      shell: apt-get update && apt-get install -y filebeat
      when: ansible_os_family == "Debian"

    - name: Backup and replace Filebeat config
      copy:
        backup: yes
        dest: "/etc/filebeat/filebeat.yml"
        content: "{{ FILEBEAT_CONF | b64decode }}"

    - name: Start FileBeat
      service:
        name: filebeat
        state: started
