- hosts: localhost
  connection: local
  tasks:
    - name: Install FileBeat
      package:
        name: filebeat
        state: latest
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - name: Ensure nc-zabbix-agent is installed on apt
      shell: apt-get update && apt-get install filebeat
      when: ansible_os_family == "Debian"

    - name: Start FileBeat
      service:
        name: filebeat
        state: started
