- hosts: localhost
  connection: local
  tasks:
    - include: ./install_filebeat/rhel.yml
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - include: ./install_filebeat/debian.yml
      when: ansible_os_family == "Debian"
