- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="Filebeat config file is not defined"
      when: config_file is not defined

    - name: Stat config file
      stat:
        path: "{{ config_file }}"
      register: stat_result

    - name: Verify config file exists
      fail: msg="Filebeat config file not exists"
      when: stat_result.stat.exists == False

    - name: Install FileBeat (rhel)
      package:
        name: filebeat
        state: latest
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - name: Install FileBeat (debian)
      shell: apt-get update && apt-get install -y filebeat
      when: ansible_os_family == "Debian"

    - name: Set filebeat config
      copy:
        remote_src: yes
        src: "{{ config_file }}"
        dest: "/etc/filebeat/filebeat.yml"
        owner: root
        mode: 0644
        force: yes
        backup: yes

    - name: Start FileBeat
      service:
        name: filebeat
        state: started
