- hosts: localhost
  connection: local
  tasks:

    - include: ./install_goaccess/rhel.yml
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - include: ./install_goaccess/debian.yml
      when: ansible_os_family == "Debian"