- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="{ mongo_port, nccheckdb_pwd } Some of them are not defined"
      when: (port is not defined) or (nccheckdb_pwd is not defined)

    - include: ./mongo_monitoring/rhel.yml
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - include: ./mongo_monitoring/debian.yml
      when: ansible_distribution == "Debian"
