- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Verify extra-vars
      fail: msg="mysql_nccheckdb_pass variable for mysql configure is not defined"
      when: mysql_nccheckdb_pass is not defined

    - name: Verify extra-vars
      fail: msg="mycnf_file variable for mysql configure is not defined"
      when: mycnf_file is not defined

    - name: Verify extra-vars
      fail: msg="mysql port is not defined"
      when: mysql_port is not defined

    - include: ./mysql_monitoring/rhel.yml
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - include: ./mysql_monitoring/debian.yml
      when: ansible_os_family == "Debian"

