- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Verify extra-vars
      fail: msg="mysql_nccheckdb_pass variable for mysql configure is not defined"
      when: mysql_nccheckdb_pass is not defined

    - name: Verify extra-vars
      fail: msg="mysql_root_pass variable for mysql configure is not defined"
      when: mysql_root_pass is not defined

    - name: Verify extra-vars
      fail: msg="mysql_port variable for mysql configure is not defined"
      when: mysql_port is not defined

#    Can not use pip to install mysql module in venv as may need to install Development Tools packages in the system first,
#      can maybe add python module to our venv and rebuild the venv package
#    - name: Ensure mysql python installed
#      pip: name=MySQL state=present

    - include: ./mysql_monitoring/rhel.yml
      when: ansible_os_family == "RedHat" or ansible_distribution == 'Amazon'

    - include: ./mysql_monitoring/debian.yml
      when: ansible_distribution == "Debian"