- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="Hostname for Opsstack config is not defined"
      when: opsstack_hostname is not defined

    - name: Save SELinux settings
      set_fact: selinux="{{ ansible_selinux }}"
      when: ansible_selinux and ansible_selinux.status != "disabled"

    - name: Disable SElinux
      selinux: state=disabled
      when: selinux is defined

    - include: ./nc-collector/rhel6.yml
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6) or ansible_distribution == 'Amazon'

    - include: ./nc-collector/rhel7.yml
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

    - include: ./nc-collector/debian8.yml
      when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 8

    - include: ./nc-collector/debian7.yml
      when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 7

    - include: ./nc-collector/ubuntu1204.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 12

    - include: ./nc-collector/ubuntu1404.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14

    - include: ./nc-collector/ubuntu1604.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16

    - name: Enable SElinux
      selinux: state="{{ selinux.config_mode }}" policy="{{ selinux.type }}"
      when: selinux is defined

    - name: Edit CNC syslog-ng configuration file for USA
      replace:
        dest: /etc/nc_collector/collector.conf
        regexp: 'https://audit\.service\.chinanetcloud\.com/cmdbapi'
        replace: 'https://audit.sys.opsstack.io/cmdbapi/cmdbapi'
        backup: no
      when: location == "USA"