- hosts: localhost
  connection: local
  tasks:
    - name: Verify extra-vars
      fail: msg="Hostname for Opsstack config is not defined"
      when: opsstack_hostname is not defined

    - name: Save SELinux settings
      set_fact: selinux="{{ ansible_selinux }}"
      when: ansible_selinux and ansible_selinux.status != "disabled"

    - name: Disable SElinux
      selinux: state=disabled
      when: selinux is defined

    - include: ./nc-collector/rhel.yml
      when: ansible_os_family == "RedHat"

    - include: ./nc-collector/debian.yml
      when: ansible_os_family == "Debian"

    - name: Enable SElinux
      selinux: state="{{ selinux.config_mode }}" policy="{{ selinux.type }}"
      when: selinux is defined

    - name: Edit CNC syslog-ng configuration file
      replace:
        dest: /etc/nc_collector/collector.conf
        regexp: 'https://audit\.service\.chinanetcloud\.com/cmdbapi'
        replace: "{{ collector_api_url }}"
        backup: no

    - name: Edit configuration zabbix credentials file
      replace:
        dest: /etc/nc_collector/collector.conf
        regexp: '/home/zabbix/conf/mysql_credentials'
        replace: '/var/lib/nc_zabbix/conf/mysql_credentials'
        backup: no
