- hosts: localhost
  connection: local
  tasks:
  - name: ensure apache monitoring folder exist
    file:
      path={{ httpd_dir }}/cnc-conf.d
      state=directory

  - name: ensure apache monitoring folder is included by httpd.conf
    lineinfile:
      dest={{ httpd_conf }}
      backup=yes
      state=present
      insertafter='^#?IncludeOptional.*'
      regexp='IncludeOptional.*'
      line='#cnc monitoring configuration\nIncludeOptional cnc-conf.d/zabbix.conf'

  - name: ensure httpd monitoring configuration
    template:
      src=../templates/httpd_zabbix.conf.j2
      dest={{ httpd_dir }}/cnc-conf.d/zabbix.conf
      owner=root
      group=root
      mode=0644

  - name: ensure zabbix vhost log folder and create zabbix log folder
    file:
      dest=/var/log/httpd/zabbix
      owner=root
      group=root
      state=directory

  - name: ensure http configuration is valid 
    command: /sbin/httpd -t
    register: httpd_test

  - name: restart httpd
    service:
      name=httpd
      state=restarted
    when:
      "{{ httpd_restart }} == 'true' and httpd_test.stdout|int == 0"

  - name: notify customer if httpd test failed
    command: echo "apache configuration syntax is incorrect, please fix it and then restart httpd"
    when:
      httpd_test.stdout|int != 0
