- hosts: localhost
  
  connection: local
  
  vars:
    mysql_slow_log: "{{ lookup('env', 'MYSQL_SLOW_LOG_PATH') }}"
    
  tasks:
    - name: Check for require variables
      fail: msg="Cannot find required variable"
      when: opsstack_hostname is undefined

    # Check if we have rsyslog, syslog-ng, or both
    - name: Detect rssylog running
      shell: ps faux | grep -v grep | grep rsyslog
      register: rsyslog_running
      changed_when: False
      ignore_errors: yes
      
    - name: Detect syslog-ng running
      shell: ps faux | grep -v grep | grep syslog-ng
      register: syslogng_running
      changed_when: False
      ignore_errors: yes
      
    - name: Check that only one is running
      fail: msg="Found both rsyslog and syslog-ng running. Aborting."
      when: rsyslog_running.rc==0 and syslogng_running.rc==0
      
    # Command Track installation  
    - name: Install pstree for command track on rhel as command track uses pstree to fetch pppid
      package:
        name: psmisc
        state: latest

    - name: Create /opt/ncscripts folder for cmd_track
      file:
        dest: /opt/ncscripts
        owner: root
        group: root
        state: directory
      
    - name: Copy nc_profile to the server for generating cmd_track
      template:
        src: ../files/nc_profile.sh
        dest: /etc/profile.d/nc_profile.sh
        owner: root
        group: root
        backup: yes
        mode: 0644
      
      
    # Check if have old rsyslog version; matches any 5.x version
    - name: Check if old rsyslog version
      shell: yum list installed rsyslog | grep ' 5' | wc -l
      register: rsyslog_oldver
      ignore_errors: yes

    # Remove old rsyslog; can't use yum as will remove deps like crontabs!
    - name: Remove old syslog
      shell: rpm -e --nodeps rsyslog
      when: rsyslog_running.rc == 0 and rsyslog_oldver.stdout == '1'

    # Have to hard-code URL for now as don't want to install repo on customer server
    - name: Install upgraded rsyslog dependencies - libestr
      yum:
        name: http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS/libestr-0.1.10-1.el6.x86_64.rpm
        state: installed
      when: rsyslog_running.rc == 0 and rsyslog_oldver.stdout == '1'

    # Have to hard-code URL for now as don't want to install repo on customer server
    - name: Install upgraded rsyslog dependencies - libfastjson
      yum:
        name: http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS/libfastjson4-0.99.5-1.el6.x86_64.rpm
        state: installed
      when: rsyslog_running.rc == 0 and rsyslog_oldver.stdout == '1'

    # Have to hard-code URL for now as don't want to install repo on customer server
    - name: Upgrade rsyslog from remote repo
      yum:
        name: http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS/rsyslog-8.28.0-1.el6.x86_64.rpm
        state: installed
      when: rsyslog_running.rc == 0 and rsyslog_oldver.stdout == '1'
      
    # Install the right config file - rsyslog block
    - name: Install CNC rsyslog configuration file
      template: src=../templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf owner=root group=root backup=yes mode=0644
      when: rsyslog_running.rc==0
      
    - name: Edit CNC rsyslog configuration file for USA
      replace:
        dest: /etc/rsyslog.conf
        regexp: '^\*\.\* @@syslog\.service\.chinanetcloud\.com:514'
        replace: '*.* @@{{ syslog_target }}:601'
        backup: no
      when: rsyslog_running.rc==0

    - name: Install CNC cmd_track configuration file
      template:
        src: ../templates/10-cmd_track.conf.j2
        dest: /etc/rsyslog.d/10-cmd_track.conf
        owner: root
        group: root
        backup: yes
        mode: 0644
      when: rsyslog_running.rc==0
      
    - name: Send mysql slow log to cnc syslog server
      template:
        src: ../templates/rmysql_slow.conf.j2
        dest: /etc/rsyslog.d/slow_log.conf
        owner: root
        group: root
        backup: yes
        mode: 0644
      when: rsyslog_running.rc==0 and mysql_slow_log != ""
      
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
      when: rsyslog_running.rc==0
      
    # Install the right config file - syslog-ng block
    - name: Install CNC syslog-ng configuration file
      template:
        src: ../templates/syslog-ng.conf.j2
        dest: /etc/syslog-ng/syslog-ng.conf
        owner: root
        group: root
        backup: yes
        mode: 0644
      when: syslogng_running.rc==0
      
    - name: Edit CNC syslog-ng configuration file for USA
      replace:
        dest: /etc/syslog-ng/syslog-ng.conf
        regexp: 'destination d_remote_netcloud \{ tcp\(syslog\.service\.chinanetcloud\.com port\(514\)\); \};'
        replace: 'destination d_remote_netcloud { tcp({{ syslog_target }} port(601)); };'
        backup: no
      when: syslogng_running.rc==0

    - name: Send mysql slow log to cnc syslog server
      lineinfile:
        dest: /etc/syslog-ng/syslog-ng.conf
        backup: yes
        state: present
        insertafter: 'EOF'
        line: 'source mysql_slow_log {file("{{ mysql_slow_log }}" default-facility(user) program_override("[mysql-slow]") flags(no-parse) );};\nlog { source(mysql_slow_log); destination(d_remote_netcloud); };'
      when: syslogng_running.rc==0 and mysql_slow_log != ""
      
    - name: Restart syslog-ng
      service:
        name: syslog-ng
        state: restarted
      when: syslogng_running.rc==0
