- hosts: localhost
  connection: local
  vars:
    mysql_slow_log: "{{ lookup('env', 'MYSQL_SLOW_LOG_PATH') }}"
  tasks:
    - name: Check for require variables
      fail: msg="Cannot find required variable"
      when: opsstack_hostname is undefined
    - name: Detect rssylog running
      shell: ps faux | grep -v grep | grep rsyslog
      register: rsyslog_running
      changed_when: False
      ignore_errors: yes
    - name: Detect syslog-ng running
      shell: ps faux | grep -v grep | grep syslog-ng
      register: syslogng_running
      changed_when: False
      ignore_errors: yes
    - name: Check that only one is running
      fail: msg="Found both rsyslog and syslog-ng running. Aborting."
      when: rsyslog_running.rc==0 and syslogng_running.rc==0
    - name: Install CNC rsyslog configuration file
      template: src=../templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf owner=root group=root backup=yes mode=0644
      when: rsyslog_running.rc==0
    - name: Send mysql slow log to cnc syslog server
      template: src=../templates/rmysql_slow.conf.j2 dest=/etc/rsyslog.d/slow_log.conf owner=root group=root backup=yes mode=0644
      when: rsyslog_running.rc==0 and mysql_slow_log != ""
    - name: Restart rsyslog
      service: name=rsyslog state=restarted
      when: rsyslog_running.rc==0
    - name: Install CNC syslog-ng configuration file
      template: src=../templates/syslog-ng.conf.j2 dest=/etc/syslog-ng/syslog-ng.conf owner=root group=root backup=yes mode=0644
      when: syslogng_running.rc==0
    - name: Send mysql slow log to cnc syslog server
      lineinfile: dest=/etc/syslog-ng/syslog-ng.conf backup=yes state=present insertafter='EOF' line='source mysql_slow_log {file("{{ mysql_slow_log }}" default-facility(user) program_override("[mysql-slow]") flags(no-parse) );};\nlog { source(mysql_slow_log); destination(d_remote_netcloud); };'
      when: syslogng_running.rc==0 and mysql_slow_log != ""
    - name: Restart syslog-ng
      service: name=syslog-ng state=restarted
      when: syslogng_running.rc==0
