---

- name: Ensure CNC repo exists
  yum: state=present name=http://repo.service.chinanetcloud.com/yum/el6/base/x86_64/nc-repo-1.0.0-1.el6.noarch.rpm

- name: Ensure nc-zabbix-agent is installed
  package: name={{item}} state=latest
  with_items:
    - nc-zabbix-agent
    - nc-zabbix-scripts

- name: Setup nc-zabbix hostname
  replace: dest=/etc/nc_zabbix/nc_zabbix_agentd.conf regexp='# Hostname=' replace="Hostname={{opsstack_hostname}}" backup=yes

- name: Restart crond to use new locations
  service: name=crond state=restarted

- name: Enable Zabbix agent
  service: name=nc-zabbix-agent state=restarted enabled=yes
