---

- name: Ensure CNC repository exist
  shell: wget -q http://repo.service.chinanetcloud.com/apt/ubuntu/pool/xenial/main/nc-repo_1.0.0-1.ubuntu+xenial_all.deb -O /tmp/nc-repo_1.0.0-1.ubuntu+xenial_all.deb

- name: Install Zabbix repository
  shell: dpkg -i /tmp/nc-repo_1.0.0-1.ubuntu+xenial_all.deb

- name: Update repository
  shell: apt-get update
  ignore_errors: true

- name: Install nc-zabbix-agent
  shell: apt-get install nc-zabbix-agent nc-zabbix-scripts -y

- name: Setup nc-zabbix hostname
  replace: dest=/etc/nc_zabbix/nc_zabbix_agentd.conf regexp='# Hostname=' replace="Hostname={{opsstack_hostname}}" backup=yes

- name: Restart crond to use new locations
  service: name=cron state=restarted

- name: Enable Zabbix agent
  service: name=nc-zabbix-agent state=restarted enabled=yes
