---

- name: Check if zabbix-agent is already installed
  shell: dpkg -l | grep 'zabbix-agent' warn=False
  register: zabbix_agent
  ignore_errors: yes

- name: Download Zabbix repository Ubuntu1204
  shell: wget -q http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb -O /tmp/zabbix-release_2.2-1+precise_all.deb
  when: zabbix_agent.rc|int != 0

- name: Install Zabbix repository
  shell: dpkg -i /tmp/zabbix-release_2.2-1+precise_all.deb
  when: zabbix_agent.rc|int != 0

- name: Update repository
  shell: apt-get update
  ignore_errors: true
  when: zabbix_agent.rc|int != 0

- name: Install zabbix-agent
  shell: apt-get install zabbix-agent
  when: zabbix_agent.rc|int != 0

- name: Install CNC Zabbix custom scripts
  shell: apt-get install nc-zabbix-custom-scripts
  ignore_errors: true

- name: Fix Zabbix config file
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp='^Hostname=(.*)$' line='Hostname={{ opsstack_hostname }}' backrefs=yes

- name: Change Zabbix Server to default
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp='^Server\=(.*)$' line='Server=127.0.0.1' backrefs=yes

- name: Remove ServerActive line
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=absent regexp='^ServerActive=(.*)$'

- name: Change Zabbix to active agent
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp='^Server\=(.*)$' line='Server=\1\nServerActive=proxy1.zabbix.service.chinanetcloud.com,proxy2.zabbix.service.chinanetcloud.com,proxy3.zabbix.service.chinanetcloud.com,proxy4.zabbix.service.chinanetcloud.com,proxy5.zabbix.service.chinanetcloud.com,proxy6.zabbix.service.chinanetcloud.com,proxy7.zabbix.service.chinanetcloud.com,proxy8.zabbix.service.chinanetcloud.com,proxy9.zabbix.service.chinanetcloud.com,proxy10.zabbix.service.chinanetcloud.com,proxy11.zabbix.service.chinanetcloud.com,proxy12.zabbix.service.chinanetcloud.com,proxy13.zabbix.service.chinanetcloud.com,proxy14.zabbix.service.chinanetcloud.com,proxy15.zabbix.service.chinanetcloud.com,proxy16.zabbix.service.chinanetcloud.com,proxy17.zabbix.service.chinanetcloud.com,proxy18.zabbix.service.chinanetcloud.com,proxy19.zabbix.service.chinanetcloud.com,proxy20.zabbix.service.chinanetcloud.com' backrefs=yes

- name: Fix Zabbix config file permissions
  file: path=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode="u=rw,g=r,o=r"

- name: Fix Zabbix HOME
  lineinfile: dest=/etc/passwd state=present regexp='^(.*)\/var\/lib\/zabbix(.*)$' line='\1/home/zabbix\2' backrefs=yes

- name: Restart crond to use new locations
  service: name=cron state=restarted

- name: Enable Zabbix agent
  service: name=zabbix-agent state=restarted enabled=yes
