---
- name: Ensure mysql python installed
  shell: apt-get install python-mysqldb -y

- name: Create nccheckdb user for mysql
  mysql_user:
    name=nccheckdb
    password={{ mysql_nccheckdb_pass }}
    priv="*.*:PROCESS,REPLICATION CLIENT,SELECT,EXECUTE"
    host=127.0.0.1
    state=present
    config_file={{ mycnf_file }}

- name: Prepare zabbix mysql_credentials
  template:
    src=../templates/client.my.cnf.j2
    dest=/var/lib/nc_zabbix/conf/mysql_credentials
    owner=zabbix
    group=zabbix
    mode=0600
  with_items:
    - user: nccheckdb
      pass: '{{ mysql_nccheckdb_pass }}'
      port: '{{ mysql_port }}'

# Import SYS Schema
- block:
    - name: Ensure git installed
      shell: apt-get install git -y

    - name: Git clone mysql sys code
      git: repo=https://github.com/mysql/mysql-sys
        dest=/tmp/mysql-sys
        accept_hostkey=yes
        force=yes

    - name: ensure performance_schema is ON
      mysql_variables: performance_schema=ON config_file={{ my_cnf_file }}

    - name: import sys database
      mysql_db: state=import name=sys target=/tmp/mysql-sys/sys_56.sql config_file={{ my_cnf_file }}

    - name: Remove mysql_sys git code
      file: path=/tmp/mysql-sys state=absent
  when: enable_sys == "Need"

- name: Remove my_cnf file
  file: path={{ mycnf_file }} state=absent




