---
- name: Ensure mysql python installed (non-amzn)
  yum:
    name=MySQL-python.x86_64
    state=present
  when:
    ansible_distribution != "Amazon"

- name: Ensure mysql python installed (amzn)
  yum:
    name=MySQL-python27.x86_64
    state=present
  when:
    ansible_distribution == "Amazon"

- name: Create nccheckdb user for mysql
  mysql_user:
    name=nccheckdb
    password={{ mysql_nccheckdb_pass }}
    priv="*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state=present
    config_file={{ mycnf_file }}

- name: Prepare zabbix mysql_credentials
  template:
    src=../../templates/client.my.cnf.j2
    dest=/home/zabbix/conf/mysql_credentials
    owner=zabbix
    group=zabbix
    mode=0600
  with_items:
    - user: nccheckdb
      pass: '{{ mysql_nccheckdb_pass }}'

- name: Remove my_cnf file
  file: path={{ mycnf_file }} state=absent

