---
- name: Create nccheckdb user for mysql
  mysql_user:
    name=nccheckdb
    password={{ mysql_nccheckdb_pass }}
    priv="*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state=present
    login_user=root
    login_password={{ mysql_root_pass }}
    login_port={{ mysql_port }}

- name: Prepare zabbix mysql_credentials
  template:
    src=../../templates/client.my.cnf.j2
    dest=/home/zabbix/conf/mysql_credentials
    owner=zabbix
    group=zabbix
    mode=0600
  with_items:
    - user: nccheckdb
      pass: '{{ mysql_nccheckdb_pass }}'
