---
- name: Ensure mysql python installed (non-amzn)
  yum:
    name=MySQL-python.x86_64
    state=present
  when:
    ansible_distribution != "Amazon" or ( ansible_distribution == "Amazon" and ansible_distribution_version == '2' )

- name: Ensure mysql python installed (amzn)
  yum:
    name=MySQL-python27.x86_64
    state=present
  when:
    ansible_distribution == "Amazon" and ansible_distribution_version != '2'

- name: Create nccheckdb user for mysql
  mysql_user:
    name=nccheckdb
    password={{ mysql_nccheckdb_pass }}
    priv="*.*:PROCESS,REPLICATION CLIENT,SELECT,EXECUTE"
    state=present
    config_file={{ mycnf_file }}

- name: Prepare zabbix mysql_credentials
  template:
    src=../templates/client.my.cnf.j2
    dest=/var/lib/nc_zabbix/conf/mysql_credentials
    owner=nc-zabbix
    group=nc-zabbix
    mode=0600
  with_items:
    - user: nccheckdb
      pass: '{{ mysql_nccheckdb_pass }}'
      port: '{{ mysql_port }}'

# Import SYS Schema
- block:
    - name: Ensure nc-mysql-sys installed
      package:
        name: nc-mysql-sys
        state: latest

    - name: sys_56.sql file use absolute path
      replace: dest=/opt/ncscripts/mysql-sys/sys_56.sql regexp='SOURCE ./' replace='SOURCE /opt/ncscripts/mysql-sys/'

    - name: ensure performance_schema is ON
      mysql_variables: variable=performance_schema value=ON config_file={{ mycnf_file }}

    - name: import sys database
      mysql_db: state=import name=all target=/opt/ncscripts/mysql-sys/sys_56.sql config_file={{ mycnf_file }}
  when: enable_sys == "Need"

- name: Remove my_cnf file
  file: path={{ mycnf_file }} state=absent
