---
  - name: register pm_status_path variable
    command: grep -q "^pm.status_path = /nc_fpm_status" /etc/php-fpm.d/www.conf
    register: pm_status_path
    ignore_errors: yes

  - name: register pm_ping variable
    command: grep -q "^ping.path = /nc_fpm_ping" /etc/php-fpm.d/www.conf
    register: pm_ping
    ignore_errors: yes

  - name: ensure pm status path enabled
    lineinfile:
      dest=/etc/php-fpm.d/www.conf
      backup=yes
      state=present
      line='pm.status_path = /nc_fpm_status'
    when:
      pm_status_path.rc|int != 0


  - name: ensure pm_ping enabled
    lineinfile:
      dest=/etc/php-fpm.d/www.conf
      backup=yes
      state=present
      line='ping.path = /nc_fpm_ping'
    when:
      pm_ping.rc|int != 0

  - name: test php-fpm configuration file
    command: /sbin/php-fpm -t
    register: php_fpm_service_status

  - name: restart php-fpm
    service:
      name=php-fpm
      state=restarted
    when:
      "{{ phpfpm_restart }} == true and php_fpm_service_status.rc|int == 0"

  - name: notify customer if php-fpm configure file test failed
    command: echo "php-fpm configuration syntax is incorrect, please fix it and then restart php-fpm"
    when:
      php_fpm_service_status.rc|int != 0
